/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pmsswing;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import DataStructures.myRuntimeData;
import java.awt.Color;

/**
 *
 * @author BSP
 */
public class EditEmp extends javax.swing.JFrame {
    myRuntimeData DS = new  myRuntimeData();
    ConDB DB = new ConDB();
    Emp_Validations VAL = new Emp_Validations();
    private Connection con;
    private Statement st;
    private DefaultTableModel tmodel;         
    public String Emp;
    int times;
    int gettingCo;

    /**
     * Creates new form MyMedicines
     */
    public EditEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addemp_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addemp_pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_emp_addtable = new javax.swing.JButton();
        addemp_empid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addemp_id = new javax.swing.JTextField();
        btn_emp_Reset1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        selected_emp_pass = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        selected_emp_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        selected_emp_empid = new javax.swing.JTextField();
        selected_emp_ID = new javax.swing.JTextField();
        btn_emp_Add = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        searchfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        del_up_empname = new javax.swing.JTextField();
        del_up_emppass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_emp_Delete = new javax.swing.JButton();
        btn_emp_Update = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        EmployeeIdCombo = new javax.swing.JComboBox<>();
        del_up_empEmpId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DS_table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyPharmacy");
        setBounds(new java.awt.Rectangle(275, 275, 400, 300));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Edit Employees");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addemp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemp_nameActionPerformed(evt);
            }
        });
        addemp_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemp_nameKeyReleased(evt);
            }
        });
        jPanel2.add(addemp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        addemp_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemp_passActionPerformed(evt);
            }
        });
        addemp_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemp_passKeyReleased(evt);
            }
        });
        jPanel2.add(addemp_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Employee ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btn_emp_addtable.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btn_emp_addtable.setText("Add");
        btn_emp_addtable.setEnabled(false);
        btn_emp_addtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_emp_addtableMouseEntered(evt);
            }
        });
        btn_emp_addtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_addtableActionPerformed(evt);
            }
        });
        jPanel2.add(btn_emp_addtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        addemp_empid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addemp_empidInputMethodTextChanged(evt);
            }
        });
        addemp_empid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addemp_empidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemp_empidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addemp_empidKeyTyped(evt);
            }
        });
        jPanel2.add(addemp_empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        addemp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemp_idActionPerformed(evt);
            }
        });
        addemp_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemp_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addemp_idKeyTyped(evt);
            }
        });
        jPanel2.add(addemp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, -1));

        btn_emp_Reset1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btn_emp_Reset1.setText("Reset");
        btn_emp_Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_Reset1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_emp_Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Employee name:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel20.setText("Add new employees");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setText("Name:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setText("ID:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        selected_emp_pass.setEditable(false);
        jPanel3.add(selected_emp_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel17.setText("Password:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        selected_emp_name.setEditable(false);
        jPanel3.add(selected_emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Employee ID:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));

        selected_emp_empid.setEditable(false);
        selected_emp_empid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                selected_emp_empidInputMethodTextChanged(evt);
            }
        });
        selected_emp_empid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                selected_emp_empidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                selected_emp_empidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                selected_emp_empidKeyTyped(evt);
            }
        });
        jPanel3.add(selected_emp_empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, -1));

        selected_emp_ID.setEditable(false);
        jPanel3.add(selected_emp_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, -1));

        btn_emp_Add.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btn_emp_Add.setText("Add to database");
        btn_emp_Add.setEnabled(false);
        btn_emp_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_emp_AddMouseEntered(evt);
            }
        });
        btn_emp_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_AddActionPerformed(evt);
            }
        });
        jPanel3.add(btn_emp_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setText("Selected items");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 270, 210));

        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchfield.setText("Click to search employee by name........");
        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        jPanel4.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Search:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "unames", "passwords", "emp_id", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SearchTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 140));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 370, 200));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        del_up_empname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                del_up_empnameInputMethodTextChanged(evt);
            }
        });
        del_up_empname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                del_up_empnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                del_up_empnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                del_up_empnameKeyTyped(evt);
            }
        });
        jPanel5.add(del_up_empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, -1));

        del_up_emppass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_up_emppassActionPerformed(evt);
            }
        });
        del_up_emppass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                del_up_emppassKeyReleased(evt);
            }
        });
        jPanel5.add(del_up_emppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("ID:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("Password:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Employee name:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        btn_emp_Delete.setText("Delete");
        btn_emp_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_DeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btn_emp_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, -1));

        btn_emp_Update.setText("Update");
        btn_emp_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_UpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btn_emp_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 70, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel19.setText("Delete or Update from DB");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        EmployeeIdCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeIdComboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeIdComboMouseExited(evt);
            }
        });
        EmployeeIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIdComboActionPerformed(evt);
            }
        });
        jPanel5.add(EmployeeIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, -1));

        del_up_empEmpId.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                del_up_empEmpIdInputMethodTextChanged(evt);
            }
        });
        del_up_empEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                del_up_empEmpIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                del_up_empEmpIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                del_up_empEmpIdKeyTyped(evt);
            }
        });
        jPanel5.add(del_up_empEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Employee ID:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 270, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        DS_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "unames", "passwords", "emp_id", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DS_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DS_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DS_table);

        jButton5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton5.setText("Show Data Entered");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel18.setText("Click on row to select and add to DB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel18)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(9, 9, 9))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 230));

        jButton6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton6.setText("< Admin");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 220, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void addemp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addemp_nameActionPerformed

    private void addemp_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemp_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addemp_passActionPerformed
    

    private void btn_emp_addtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_addtableActionPerformed
        //Adding to datastructure 
        String uname=addemp_name.getText(),upass=addemp_pass.getText();
        int empID = Integer.parseInt(addemp_empid.getText()),ID= Integer.parseInt(addemp_id.getText());
        DS.addUser(uname,upass,empID,ID);    
        JOptionPane.showMessageDialog(null, "Data added to Data Structure");
            addemp_name.setText("");
            addemp_pass.setText("");
            addemp_empid.setText("");
            addemp_id.setText("");
            addemp_empid.setBackground(Color.WHITE);
            addemp_id.setBackground(Color.WHITE);
            addemp_name.setBackground(Color.WHITE);
            addemp_pass.setBackground(Color.WHITE);
        try{
            if(this.DS == null){
                JOptionPane.showMessageDialog(null, "No data found");
            }
            DS.show();
            btn_emp_Add.setEnabled(true);
            btn_emp_addtable.setEnabled(false);
        }
        catch (Exception e){
            System.out.print(e);
        }    
    }//GEN-LAST:event_btn_emp_addtableActionPerformed
    
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        if(gettingCo==1){
        gettingCo = 0;
        EmployeeIdCombo.removeAllItems();}
    }//GEN-LAST:event_jPanel3MouseEntered

    private void btn_emp_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_UpdateActionPerformed
        // TODO add your handling code here:
        try{
        int empI = Integer.parseInt(del_up_empEmpId.getText());
        String n = del_up_empname.getText();
        String p = del_up_emppass.getText();
        if(VAL.empid_DB_val(empI) == false && VAL.NPIString_val(n) == false && VAL.NPIString_val(p) == false ){
            JOptionPane.showMessageDialog(null, "Validate first!");
            return;
        }
        if(JOptionPane.showConfirmDialog(null,"Are you sure, you want to update "+selected_emp_name.getText()+"?","Pharmacy Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            DB.Update(n,p,empI,Integer.parseInt(EmployeeIdCombo.getSelectedItem().toString()));
            JOptionPane.showMessageDialog(null, "UPDATE SUCCESSFULLY!");
            SettingUpDel();
            del_up_empEmpId.setBackground(Color.WHITE);
            del_up_empname.setBackground(Color.WHITE);
            del_up_emppass.setBackground(Color.WHITE);
        }}
        catch(Exception e){
            
        }
    }//GEN-LAST:event_btn_emp_UpdateActionPerformed

    private void btn_emp_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_DeleteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Are you sure, you want to delete "+selected_emp_name.getText()+"?","Pharmacy Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            DB.Delete(Integer.parseInt(EmployeeIdCombo.getSelectedItem().toString()));
            EmployeeIdCombo.removeItemAt(EmployeeIdCombo.getSelectedIndex());
            del_up_empEmpId.setText("");
            del_up_emppass.setText("");
            del_up_empname.setText("");
            SettingUpDel();
        }
    }//GEN-LAST:event_btn_emp_DeleteActionPerformed

    private void btn_emp_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_AddActionPerformed
        // TODO add your handling code here:
        String uname=selected_emp_name.getText(),upass=selected_emp_pass.getText();
        try{
        int empID = Integer.parseInt(selected_emp_empid.getText());
        int Id = Integer.parseInt(selected_emp_ID.getText());
        if(JOptionPane.showConfirmDialog(null,"Are you sure, you want to add "+selected_emp_name.getText()+"to database?","Pharmacy Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        DS.delbyEmp(empID);
        DB.AddtoDB(uname,upass,Id,empID);
        selected_emp_name.setText("");
        selected_emp_pass.setText("");
        selected_emp_ID.setText("");
        selected_emp_empid.setText("");
        }}
        catch(Exception e){
            
        }
    }//GEN-LAST:event_btn_emp_AddActionPerformed

    private void addemp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addemp_idActionPerformed

    
    private void btn_emp_Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_Reset1ActionPerformed
        // TODO add your handling code here:
        addemp_id.setText("");
        addemp_name.setText("");
        addemp_pass.setText("");
        addemp_empid.setText("");
    }//GEN-LAST:event_btn_emp_Reset1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DS.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addemp_empidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_empidKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_addemp_empidKeyTyped

    private void addemp_empidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_empidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addemp_empidKeyPressed

    private void addemp_empidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_addemp_empidInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addemp_empidInputMethodTextChanged

    private void addemp_empidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_empidKeyReleased
        // TODO add your handling code here:
        try{
        int empID = Integer.parseInt(addemp_empid.getText());
        if(VAL.NPIString_val(addemp_empid.getText())== false  || VAL.empid_DB_val(empID) == false || DS.empid_DS_val(empID) == false ){
            addemp_empid.setBackground(Color.red);
        }
        else{
            addemp_empid.setBackground(Color.GREEN);
        }}
        catch (Exception e){
            
        }
    }//GEN-LAST:event_addemp_empidKeyReleased

    private void addemp_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_idKeyReleased
        // TODO add your handling code here:
        try{
        int ID = Integer.parseInt(addemp_id.getText());
        if(addemp_id.getText().isEmpty() || VAL.ID_DB_val(ID) == false || DS.ID_DS_val(ID) == false ){
            addemp_id.setBackground(Color.red);
        }
        else{
            addemp_id.setBackground(Color.GREEN);
        }}
        catch(Exception e){
            
        }
    }//GEN-LAST:event_addemp_idKeyReleased

    private void addemp_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_idKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_addemp_idKeyTyped

    private void btn_emp_addtableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_emp_addtableMouseEntered
        // TODO add your handling code here:
        try{
        int EID = Integer.parseInt(addemp_empid.getText());
        int ID = Integer.parseInt(addemp_id.getText());
        if(VAL.empid_DB_val(EID) && VAL.ID_DB_val(ID) && VAL.ID_string_val(addemp_id.getText()) && VAL.NPIString_val(addemp_empid.getText()) && VAL.NPIString_val(addemp_name.getText()) && VAL.NPIString_val(addemp_pass.getText())){
            btn_emp_addtable.setEnabled(true);
        }
        else{
            btn_emp_addtable.setEnabled(false);
        }}
        catch(Exception e){
            
        }
    }//GEN-LAST:event_btn_emp_addtableMouseEntered

    private void selected_emp_empidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_selected_emp_empidInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selected_emp_empidInputMethodTextChanged

    private void selected_emp_empidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selected_emp_empidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_selected_emp_empidKeyPressed

    private void selected_emp_empidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selected_emp_empidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_selected_emp_empidKeyReleased

    private void selected_emp_empidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selected_emp_empidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_selected_emp_empidKeyTyped

    private void DS_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DS_tableMouseClicked
        // getting selected item
        tmodel = (DefaultTableModel)DS_table.getModel();
        int selectedData = DS_table.getSelectedRow();
        selected_emp_name.setText(tmodel.getValueAt(selectedData, 0).toString());
        selected_emp_pass.setText(tmodel.getValueAt(selectedData, 1).toString());
        selected_emp_empid.setText(tmodel.getValueAt(selectedData, 2).toString());
        selected_emp_ID.setText(tmodel.getValueAt(selectedData, 3).toString());
        tmodel.removeRow(selectedData);
    }//GEN-LAST:event_DS_tableMouseClicked

    private void btn_emp_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_emp_AddMouseEntered
        // TODO add your handling code here:
        String ID = selected_emp_ID.getText();
        String Name = selected_emp_name.getText();
        String Pass = selected_emp_pass.getText();
        String EmpID = selected_emp_empid.getText();
        if(ID.isEmpty() || Name.isEmpty() || Pass.isEmpty() || EmpID.isEmpty()){
            btn_emp_Add.setEnabled(false);
        }
        else{
            btn_emp_Add.setEnabled(true);
        }
    }//GEN-LAST:event_btn_emp_AddMouseEntered

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked
        // TODO add your handling code here:
        searchfield.setText("");
    }//GEN-LAST:event_searchfieldMouseClicked

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
        DB.SearchEmp(SearchTable,searchfield.getText());
    }//GEN-LAST:event_searchfieldActionPerformed

    private void addemp_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_nameKeyReleased
        // TODO add your handling code here:
        if(VAL.NPIString_val(addemp_name.getText()) == false){
            addemp_name.setBackground(Color.red);
        }
        else{
            addemp_name.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_addemp_nameKeyReleased

    private void addemp_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemp_passKeyReleased
        // TODO add your handling code here:
        if(VAL.NPIString_val(addemp_pass.getText()) == false){
            addemp_pass.setBackground(Color.red);
        }
        else{
            addemp_pass.setBackground(Color.GREEN);
        }        
    }//GEN-LAST:event_addemp_passKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Admin back = new Admin();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void del_up_emppassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_up_emppassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_emppassActionPerformed

    private void del_up_emppassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_emppassKeyReleased
        // TODO add your handling code here:
        if(VAL.NPIString_val(del_up_emppass.getText()) == false){
            del_up_emppass.setBackground(Color.red);
        }
        else{
            del_up_emppass.setBackground(Color.GREEN);
        }        
    }//GEN-LAST:event_del_up_emppassKeyReleased

    private void del_up_empnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_del_up_empnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_empnameInputMethodTextChanged

    private void del_up_empnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_empnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_empnameKeyPressed

    private void del_up_empnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_empnameKeyReleased
        // TODO add your handling code here:
        if(VAL.NPIString_val(del_up_empname.getText()) == false){
            del_up_empname.setBackground(Color.red);
        }
        else{
            del_up_empname.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_del_up_empnameKeyReleased

    private void del_up_empnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_empnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_empnameKeyTyped

    private void EmployeeIdComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeIdComboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIdComboMouseEntered

    private void EmployeeIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIdComboActionPerformed
        // TODO add your handling code here:
        SettingUpDel();
    }//GEN-LAST:event_EmployeeIdComboActionPerformed

    private void del_up_empEmpIdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_del_up_empEmpIdInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_empEmpIdInputMethodTextChanged

    private void del_up_empEmpIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_empEmpIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_empEmpIdKeyPressed

    private void del_up_empEmpIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_empEmpIdKeyReleased
        // TODO add your handling code here:
        if(VAL.NPIString_val(del_up_empEmpId.getText()) == false){
            del_up_empEmpId.setBackground(Color.red);
        }
        else{
            del_up_empEmpId.setBackground(Color.GREEN);
        }        
    }//GEN-LAST:event_del_up_empEmpIdKeyReleased

    private void del_up_empEmpIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_del_up_empEmpIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_del_up_empEmpIdKeyTyped

    private void EmployeeIdComboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeIdComboMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIdComboMouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        if(gettingCo == 0){
        GettingCombo();
        gettingCo=1;
        }
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        if(gettingCo==1){
        gettingCo = 0;
        EmployeeIdCombo.removeAllItems();}
    }//GEN-LAST:event_jPanel2MouseEntered

    //Setting for del/up
    private void SettingUpDel(){
        try{
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\DSA Theory Summers\\Project\\ODBC connectivity issue resolved\\MediDB.accdb");
            st = con.createStatement();
            String query = "Select * from login where ID = '"+EmployeeIdCombo.getSelectedItem()+ "'";
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                del_up_emppass.setText(rs.getString("passwords"));
                del_up_empname.setText(rs.getString("unames"));
                del_up_empEmpId.setText(String.valueOf(rs.getInt("emp_id")));
            }
            con.close();
        }
        catch (Exception e){
            
        }
    }
    //Getting data in combo
    private void GettingCombo(){
        try{
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\DSA Theory Summers\\Project\\ODBC connectivity issue resolved\\MediDB.accdb");
            st = con.createStatement();
            String query = "Select ID from login";
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                int ID = rs.getInt("ID");
                String IDs = String.valueOf(ID);
                EmployeeIdCombo.addItem(IDs);
            }
            con.close();
        }
        catch (Exception e){
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmp().setVisible(true);
            }
        });
    }

    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable DS_table;
    private javax.swing.JComboBox<String> EmployeeIdCombo;
    private javax.swing.JTable SearchTable;
    private javax.swing.JTextField addemp_empid;
    private javax.swing.JTextField addemp_id;
    private javax.swing.JTextField addemp_name;
    private javax.swing.JTextField addemp_pass;
    private javax.swing.JButton btn_emp_Add;
    private javax.swing.JButton btn_emp_Delete;
    private javax.swing.JButton btn_emp_Reset1;
    private javax.swing.JButton btn_emp_Update;
    private javax.swing.JButton btn_emp_addtable;
    private javax.swing.JTextField del_up_empEmpId;
    private javax.swing.JTextField del_up_empname;
    private javax.swing.JTextField del_up_emppass;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchfield;
    private javax.swing.JTextField selected_emp_ID;
    private javax.swing.JTextField selected_emp_empid;
    private javax.swing.JTextField selected_emp_name;
    private javax.swing.JTextField selected_emp_pass;
    // End of variables declaration//GEN-END:variables
}
