/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pmsswing;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author BSP
 */
public class MyMedicines extends javax.swing.JFrame {
    private Statement st;
    private Connection con;
    private DefaultTableModel tmodel;

    /**
     * Creates new form MyMedicines
     */
    public MyMedicines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addMed_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addMed_quan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addMed_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        addMed_dosage = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addMed_make = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        addMed_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        data_price = new javax.swing.JTextField();
        data_make = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        data_dosage = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        data_combo = new javax.swing.JComboBox<>();
        delete_btn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        data_quan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        data_name = new javax.swing.JTextField();
        Rf_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyPharmacy");
        setBounds(new java.awt.Rectangle(275, 275, 400, 300));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Edit Medicines");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jScrollPane2.setViewportView(table);
        ConnectToDatabase();
        Display(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 420, 330));

        jButton3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton3.setText("< Admin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 120, -1));

        jButton4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton4.setText("Get data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addMed_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMed_nameActionPerformed(evt);
            }
        });
        jPanel2.add(addMed_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Medicine name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        addMed_quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMed_quanActionPerformed(evt);
            }
        });
        addMed_quan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addMed_quanKeyTyped(evt);
            }
        });
        jPanel2.add(addMed_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Quantity:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        addMed_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMed_priceActionPerformed(evt);
            }
        });
        addMed_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addMed_priceKeyTyped(evt);
            }
        });
        jPanel2.add(addMed_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Price:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jButton6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel12.setText("Dosage:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        addMed_dosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMed_dosageActionPerformed(evt);
            }
        });
        addMed_dosage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addMed_dosageKeyTyped(evt);
            }
        });
        jPanel2.add(addMed_dosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setText("Make:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        addMed_make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMed_makeActionPerformed(evt);
            }
        });
        jPanel2.add(addMed_make, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setText("Add new medicine");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        addMed_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMed_idActionPerformed(evt);
            }
        });
        addMed_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addMed_idKeyTyped(evt);
            }
        });
        jPanel2.add(addMed_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Medicine ID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 270, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                data_priceKeyTyped(evt);
            }
        });
        jPanel3.add(data_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, -1));
        jPanel3.add(data_make, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 90, -1));

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, -1));

        data_dosage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                data_dosageKeyTyped(evt);
            }
        });
        jPanel3.add(data_dosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 90, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Make:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setText("Name:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        data_combo.setToolTipText("");
        data_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                data_comboItemStateChanged(evt);
            }
        });
        data_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_comboActionPerformed(evt);
            }
        });
        jPanel3.add(data_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, -1));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel3.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 70, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel18.setText("Price:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setText("Select:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        data_quan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                data_quanKeyTyped(evt);
            }
        });
        jPanel3.add(data_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Dosage:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel17.setText("Quantity:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel3.add(data_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 240));

        Rf_btn.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Rf_btn.setText("Refresh");
        Rf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rf_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Rf_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 240, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
        
    public String Med;
    int times;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Getting data in combo box
        try{        
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\DSA Theory Summers\\Project\\ODBC connectivity issue resolved\\MediDB.accdb");
            //create statement
            st = con.createStatement();  
            ResultSet myRes = st.executeQuery("Select * from MediInfo");
        if (times>0){
            return;
        }
        while (myRes.next()){
            times++;
            Med = myRes.getString("MedicineID");     
            data_combo.addItem(Med);
        }
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Admin bck = new Admin();
        bck.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addMed_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMed_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_nameActionPerformed

    private void addMed_quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMed_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_quanActionPerformed

    private void addMed_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMed_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_priceActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        addMed_id.setText("");
        addMed_price.setText("");
        addMed_name.setText("");
        addMed_quan.setText("");
        addMed_dosage.setText("");
        addMed_make.setText("");        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addMed_dosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMed_dosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_dosageActionPerformed

    private void addMed_makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMed_makeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_makeActionPerformed

    private void data_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_comboActionPerformed
        // TODO add your handling code here:
        String MedN,MedM;
        int MedQ,MedD;
        float MedP;
        String select = data_combo.getSelectedItem().toString();
        try{        
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\DSA Theory Summers\\Project\\ODBC connectivity issue resolved\\MediDB.accdb");
            //create statement
            st = con.createStatement();  
            ResultSet myRes = st.executeQuery("Select * from MediInfo where MedicineId="+select);
        
        while (myRes.next()){
            MedN = myRes.getString("MediTitle"); 
            MedQ = myRes.getInt("Qty");
            MedP = myRes.getFloat("Price");
            MedD = myRes.getInt("DosAge");
            MedM = myRes.getString("Make");
            data_name.setText(MedN);
            data_quan.setText(String.valueOf(MedQ));
            data_price.setText(String.valueOf(MedP));
            data_dosage.setText(String.valueOf(MedD));
            data_make.setText(MedM);
        }
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_data_comboActionPerformed

    private void data_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_data_comboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_data_comboItemStateChanged

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // adding to database
        String N,M;
        int Id,Q,D;
        float P;
        Id=Integer.parseInt(addMed_id.getText());
        N=addMed_name.getText();
        Q=Integer.parseInt(addMed_quan.getText());
        P=Float.parseFloat(addMed_price.getText());
        D=Integer.parseInt(addMed_dosage.getText());
        M=addMed_make.getText();
        //Check if any feild is empty?
        if(Id == 0 || N.isEmpty() || Q == 0 || P == 0 || D == 0 || M.isEmpty() ){
            JOptionPane.showMessageDialog(null, "All Fields must be filled");
            return;
        }
            if(JOptionPane.showConfirmDialog(null,"Are you sure, you want to add "+addMed_name.getText()+"?","Pharmacy Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            ConnectToDatabase();
        Add(Id,N,Q,P,D,M);
        Display(table);
        addMed_id.setText("");
        addMed_price.setText("");
        addMed_name.setText("");
        addMed_quan.setText("");
        addMed_dosage.setText("");
        addMed_make.setText("");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void addMed_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMed_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_idActionPerformed

    private void Rf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rf_btnActionPerformed
        // TODO add your handling code here:
        ConnectToDatabase();
        Display(table);
    }//GEN-LAST:event_Rf_btnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ConnectToDatabase();
        Update(Integer.parseInt(data_combo.getSelectedItem().toString()),data_name.getText(),Integer.parseInt(data_quan.getText()),Float.parseFloat(data_price.getText()),Integer.parseInt(data_dosage.getText()),data_make.getText());
        Display(table);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
                if(JOptionPane.showConfirmDialog(null,"Are you sure, you want to delete "+data_name.getText()+"?","Pharmacy Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            ConnectToDatabase();
                    Delete(Integer.parseInt(data_combo.getSelectedItem().toString()));
                    data_combo.removeItemAt(data_combo.getSelectedIndex());
                    ConnectToDatabase();
                    Display(table);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void data_quanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_quanKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_data_quanKeyTyped

    private void data_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_priceKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_data_priceKeyTyped

    private void data_dosageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_dosageKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_data_dosageKeyTyped

    private void addMed_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMed_idKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }        
    }//GEN-LAST:event_addMed_idKeyTyped

    private void addMed_quanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMed_quanKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_quanKeyTyped

    private void addMed_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMed_priceKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_priceKeyTyped

    private void addMed_dosageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMed_dosageKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addMed_dosageKeyTyped
    
        private void Delete (int Id)
	{
		try
		{
			//prepare statement
			String qry = "Delete from MediInfo where MedicineID = ?";
			PreparedStatement ps = con.prepareStatement(qry);
			ps.setInt(1, Id);

			ps.executeUpdate();
		}
		catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
	}
    
    
    
    	private void Update (int Id, String N, int Q, float P, int D,String M)
	{
		try
		{
			//prepare statement
			String qry = "Update MediInfo set MedicineID = ?, MediTitle = ?, Qty = ?, Price = ?, DosAge = ?, Make = ? where MedicineID = ?";
			PreparedStatement ps = con.prepareStatement(qry);

			ps.setInt(1, Id);
			ps.setString(2, N);
			ps.setInt(3, Q);
			ps.setFloat(4, P);
                        ps.setInt(5, D);
			ps.setString(6, M);
                        
                        ps.setInt(7, Id);
			ps.executeUpdate();
		}
		catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
	}
    
    private void Display(JTable TableSupply){
            try{
                Statement disstat = con.createStatement();
                String query = "Select * from MediInfo";
                ResultSet rs =disstat.executeQuery(query);
                TableSupply.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }
    private void ConnectToDatabase ()
	{
		try
		{
			con = DriverManager.getConnection("jdbc:ucanaccess://D:\\DSA Theory Summers\\Project\\ODBC connectivity issue resolved\\MediDB.accdb");
			st = con.createStatement();
		}
		catch (Exception e) {System.out.println(e);}
    }
        
    private void Add(int Id, String name, int qty, float price, int dos, String make ){
        try
		{
			//prepare statement
			String qry = "Insert into MediInfo values (?, ?, ?, ?, ?, ?)";
                        
			PreparedStatement ps = con.prepareStatement(qry);
			ps.setInt(1, Id);
			ps.setString(2, name);
			ps.setInt(3, qty);
			ps.setFloat(4,price);
                        ps.setInt(5,dos);
                        ps.setString(6,make);
                        //JOptionPane.showConfirmDialog(this, "Are you sure?");
			ps.executeUpdate();
		}
		catch(Exception e) {System.out.println(e + "\t" + e.getMessage());	}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMedicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rf_btn;
    private javax.swing.JTextField addMed_dosage;
    private javax.swing.JTextField addMed_id;
    private javax.swing.JTextField addMed_make;
    private javax.swing.JTextField addMed_name;
    private javax.swing.JTextField addMed_price;
    private javax.swing.JTextField addMed_quan;
    private javax.swing.JComboBox<String> data_combo;
    private javax.swing.JTextField data_dosage;
    private javax.swing.JTextField data_make;
    private javax.swing.JTextField data_name;
    private javax.swing.JTextField data_price;
    private javax.swing.JTextField data_quan;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
